backend:
  name: github
  repo: hamish/scout-events-website # Updated with actual GitHub repo
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://api.netlify.com # Path to ext auth provider
  auth_endpoint: auth # Path to ext auth provider

# Media files will be stored in the repo under static/images/uploads
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

# Site URL for preview functionality
site_url: https://scout-events-website.netlify.app # Replace with actual site URL

# Collections define the structure for different content types
collections:
  # Events collection
  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
        hint: "Enter a descriptive title for the event"
      - label: "Start Date"
        name: "start_date"
        widget: "datetime"
        required: true
        date_format: "YYYY-MM-DD"
        time_format: false
        picker_utc: false
        hint: "Select the date when the event starts"
      - label: "End Date"
        name: "end_date"
        widget: "datetime"
        required: false
        date_format: "YYYY-MM-DD"
        time_format: false
        picker_utc: false
        hint: "Leave blank if the event ends on the same day as it starts"
      - label: "Start Time"
        name: "start_time"
        widget: "string"
        required: true
        pattern: ["^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$", "Please enter time in HH:MM format (24-hour), e.g., 19:00"]
        hint: "Enter start time in 24-hour format (e.g., 19:00 for 7:00 PM)"
      - label: "End Time"
        name: "end_time"
        widget: "string"
        required: false
        pattern: ["^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$", "Please enter time in HH:MM format (24-hour), e.g., 21:00"]
        hint: "Enter end time in 24-hour format. Leave blank to show only start time"
      - label: "Location"
        name: "location"
        widget: "string"
        required: true
        hint: "Enter the full address or location name where the event will take place"
      - label: "Event Type"
        name: "event_type"
        widget: "select"
        required: true
        hint: "Select the category that best describes this event. To modify available options, edit Site Configuration → Event Configuration."
        options:
          - {label: "Meeting", value: "meeting"}
          - {label: "Camping", value: "camping"}
          - {label: "Community Service", value: "community_service"}
          - {label: "Fundraising", value: "fundraising"}
          - {label: "Social Event", value: "social"}
          - {label: "Training", value: "training"}
          - {label: "Competition", value: "competition"}
      - label: "Age Groups"
        name: "age_groups"
        widget: "select"
        required: true
        multiple: true
        min: 1
        hint: "Select all age groups that can participate in this event. To modify available options, edit Site Configuration → Event Configuration."
        options:
          - {label: "Beavers (5-7 years)", value: "beavers"}
          - {label: "Cubs (8-10 years)", value: "cubs"}
          - {label: "Scouts (11-14 years)", value: "scouts"}
          - {label: "Venturers (15-17 years)", value: "venturers"}
          - {label: "Rovers (18-25 years)", value: "rovers"}
          - {label: "All Ages", value: "all"}
      - label: "Description"
        name: "description"
        widget: "markdown"
        required: true
        hint: "Provide a detailed description of the event. You can use markdown formatting for bold, italic, lists, etc."
        buttons: ["bold", "italic", "code", "link", "heading-two", "heading-three", "quote", "bulleted-list", "numbered-list"]
      - label: "Featured Image"
        name: "featured_image"
        widget: "image"
        required: false
        hint: "Upload an image to display with the event (optional). Recommended size: 800x400 pixels"
        media_library:
          config:
            max_file_size: 2048000 # 2MB limit
      - label: "Registration Required"
        name: "registration_required"
        widget: "boolean"
        default: false
        required: false
        hint: "Toggle this on if participants need to register for the event"
      - label: "Registration Link"
        name: "registration_link"
        widget: "string"
        required: false
        pattern: ["^https?://.*", "Please enter a valid URL starting with http:// or https://"]
        hint: "Enter the URL where people can register for the event (only if registration is required)"
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: false
        required: false
        hint: "Keep this event as a draft (not published) until you're ready to make it live"

  # Pages collection for static content
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
        hint: "Enter the page title that will appear in navigation and as the main heading"
      - label: "Type"
        name: "type"
        widget: "hidden"
        default: "page"
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
        hint: "Brief description for SEO and page summary (optional)"
      - label: "Menu Order"
        name: "menu_order"
        widget: "number"
        required: false
        default: 10
        hint: "Order in navigation menu (lower numbers appear first). Default is 10."
      - label: "Featured Image"
        name: "featured_image"
        widget: "image"
        required: false
        hint: "Upload an image to display at the top of the page (optional)"
        media_library:
          config:
            max_file_size: 2048000 # 2MB limit
      - label: "Content"
        name: "body"
        widget: "markdown"
        required: true
        hint: "Page content using markdown formatting. You can add headings, lists, links, images, and more."
        buttons: ["bold", "italic", "code", "link", "heading-two", "heading-three", "heading-four", "quote", "bulleted-list", "numbered-list"]
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: false
        required: false
        hint: "Keep this page as a draft (not published) until you're ready to make it live"

  # Site configuration
  - name: "config"
    label: "Site Configuration"
    files:
      - label: "Site Settings"
        name: "site"
        file: "data/site.yml"
        fields:
          - label: "Site Title"
            name: "title"
            widget: "string"
            required: true
            hint: "The main title of your website that appears in the browser tab and header"
          - label: "Site Description"
            name: "description"
            widget: "text"
            required: true
            hint: "A brief description of your scout group and website for search engines and social media"
          - label: "Contact Email"
            name: "contact_email"
            widget: "string"
            required: true
            pattern: ["^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$", "Please enter a valid email address"]
            hint: "Main contact email address for your scout group"
          - label: "Phone Number"
            name: "phone"
            widget: "string"
            required: false
            hint: "Contact phone number (optional)"
          - label: "Address"
            name: "address"
            widget: "text"
            required: false
            hint: "Physical address of your scout hall or meeting location (optional)"
          - label: "Social Media"
            name: "social_media"
            widget: "object"
            required: false
            collapsed: false
            hint: "Links to your social media profiles (all optional)"
            fields:
              - label: "Facebook URL"
                name: "facebook"
                widget: "string"
                required: false
                pattern: ["^https?://.*", "Please enter a valid URL starting with http:// or https://"]
                hint: "Full URL to your Facebook page"
              - label: "Instagram URL"
                name: "instagram"
                widget: "string"
                required: false
                pattern: ["^https?://.*", "Please enter a valid URL starting with http:// or https://"]
                hint: "Full URL to your Instagram profile"
              - label: "Twitter URL"
                name: "twitter"
                widget: "string"
                required: false
                pattern: ["^https?://.*", "Please enter a valid URL starting with http:// or https://"]
                hint: "Full URL to your Twitter profile"
          - label: "Group Information"
            name: "group_info"
            widget: "object"
            required: false
            collapsed: false
            hint: "Information about your scout group"
            fields:
              - label: "Group Name"
                name: "group_name"
                widget: "string"
                required: true
                hint: "Official name of your scout group"
              - label: "Meeting Times"
                name: "meeting_times"
                widget: "string"
                required: false
                hint: "When and how often your group meets (e.g., 'Fridays 7:00 PM - 9:00 PM')"
              - label: "Age Ranges"
                name: "age_ranges"
                widget: "string"
                required: false
                hint: "Age ranges your group serves (e.g., 'Ages 5-25')"
              - label: "Meeting Location"
                name: "meeting_location"
                widget: "string"
                required: false
                hint: "Name or description of where your group meets (e.g., 'Scout Hall', 'Community Center')"
          - label: "Event Configuration"
            name: "event_config"
            widget: "object"
            required: false
            collapsed: false
            hint: "Configure available event types and age groups for your site"
            fields:
              - label: "Event Types"
                name: "event_types"
                widget: "list"
                required: true
                hint: "Define the types of events that can be selected when creating events"
                fields:
                  - label: "Label"
                    name: "label"
                    widget: "string"
                    required: true
                    hint: "Display name for this event type (e.g., 'Meeting')"
                  - label: "Value"
                    name: "value" 
                    widget: "string"
                    required: true
                    hint: "Internal value for this event type (e.g., 'meeting'). Use lowercase with underscores."
                default:
                  - {label: "Meeting", value: "meeting"}
                  - {label: "Camping", value: "camping"}
                  - {label: "Community Service", value: "community_service"}
                  - {label: "Fundraising", value: "fundraising"}
                  - {label: "Social Event", value: "social"}
                  - {label: "Training", value: "training"}
                  - {label: "Competition", value: "competition"}
              - label: "Age Groups"
                name: "age_groups"
                widget: "list"
                required: true
                hint: "Define the age groups that can be selected for events"
                fields:
                  - label: "Label"
                    name: "label"
                    widget: "string"
                    required: true
                    hint: "Display name for this age group (e.g., 'Cubs (8-10 years)')"
                  - label: "Value"
                    name: "value"
                    widget: "string"
                    required: true
                    hint: "Internal value for this age group (e.g., 'cubs'). Use lowercase."
                default:
                  - {label: "Beavers (5-7 years)", value: "beavers"}
                  - {label: "Cubs (8-10 years)", value: "cubs"}
                  - {label: "Scouts (11-14 years)", value: "scouts"}
                  - {label: "Venturers (15-17 years)", value: "venturers"}
                  - {label: "Rovers (18-25 years)", value: "rovers"}
                  - {label: "All Ages", value: "all"}

# Editorial workflow for content review (optional)
publish_mode: editorial_workflow

# Enable preview functionality
show_preview_links: true

# Logo for the CMS interface
logo_url: /images/scout-logo.png # Optional: Add your scout group logo

# Local backend for development (uncomment for local testing)
# local_backend: true

# For local development without OAuth, you can also use:
# backend:
#   name: git-gateway